import type { Metadata } from 'next';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import Toolbar from '@/components/Toolbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div>
        <Navbar />
      </div>
      <div className='hidden lg:flex'>
        <Sidebar />
      </div>
      {children}
      <div className='flex lg:hidden'>
        <Toolbar />
      </div>
    </div>
  );
}
